version: "3.3"

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
  web:
    build: .
    command: sh -c "gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    volumes:
      - static:/usr/src/app/media
    expose:
      - 8000
    depends_on:
      - db
      - redis
  daphne:
    build: .
    command: sh -c "daphne -b 0.0.0.0 -p 8001 core.asgi:application"
    expose:
      - 8001
    depends_on:
      - db
      - redis
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static:/usr/src/app/media
  redis:
    image: redis:7.0.5-alpine
    ports:
      - '6379:6379'

  worker:
    build: .
    command: celery -A user.email_service.tasks worker -l INFO --pool=solo
    volumes:
      - .:/code
    depends_on:
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}

volumes:
  static:
  db:
