version: "3.3"

services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - EXPIRES_IN=${EXPIRES_IN}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    ports:
      - '9000:9000'
  web:
    build: .
    command: sh -c "gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    volumes:
      - .:/code
      - static:/var/www/html/cms/static
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static:/var/www/html/cms/static

volumes:
  static:
